<?php use Magento\Framework\App\Action\Action; ?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $_productCollection = $block->getLoadedProductCollection(); ?>
<?php if (!$_productCollection->count()):?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else:?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    $viewMode = $block->getMode();

    /**
     * @var \Magento\Catalog\Block\Product\ListProduct $productListBlock
     */
    $productListBlock = $block->getChildBlock('infinite-scroll.category.products.list');
    $productListBlock->setData('product_collection', $_productCollection);
    $productListBlock->setData('view_mode', $viewMode);
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items" data-mage-init='{
            "userScrollProcessor": {
                "currentCategoryId": "<?= $_productCollection->getFirstItem()->getData('category_id') ?>"
            },
            "ajaxCategoryProductsProcessor": {}
        }'>
            <?= $productListBlock->toHtml() ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()):?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $escaper->escapeJs($_productCollection->getLastItem()->getSku()) ?>"
                    }
                }
            }
            </script>
    <?php endif; ?>
<?php endif; ?>
