<?php use Magento\Framework\App\Action\Action; ?>
<?php
    /**
      * @var \Magento\Catalog\Block\Product\ListProduct $block
      * @var \Magento\Framework\Escaper $escaper
      * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
     */
?>
<?php
$productCollection = $block->getData('product_collection') ?? $block->getLoadedProductCollection();
$pos = $block->getData('position') ?? $block->getPositioned();
/** @var \Magento\Catalog\Helper\Output $_helper */
$helper = $block->getData('outputHelper');
$viewMode = $block->getData('view_mode') ?? $block->getMode();

if ($viewMode === 'grid') {
    $imageDisplayArea = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $imageDisplayArea = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}
?>
<?php /** @var $product \Magento\Catalog\Model\Product */ ?>
<?php foreach ($productCollection as $product):?>
    <li class="item product product-item">
        <div class="product-item-info"
             id="product-item-info_<?= /* @noEscape */ $product->getId() ?>"
             data-container="product-<?= /* @noEscape */ $viewMode ?>">
            <?php
            $productImage = $block->getImage($product, $imageDisplayArea);
            if ($pos != null) {
                $position = 'left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;';
            }
            ?>
            <?php // Product Image ?>
            <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
               class="product photo product-item-photo"
               tabindex="-1">
                <?= $productImage->toHtml() ?>
            </a>
            <div class="product details product-item-details">
                <?php
                $_productNameStripped = $block->stripTags($product->getName(), null, true);
                ?>
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                        <?=/* @noEscape */ $helper->productAttribute($product, $product->getName(), 'name')?>
                    </a>
                </strong>
                <?= $block->getReviewsSummaryHtml($product, $templateType) ?>
                <?= /* @noEscape */ $block->getProductPrice($product) ?>
                <?php if ($product->isAvailable()):?>
                    <?= $block->getProductDetailsHtml($product) ?>
                <?php endif; ?>

                <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                        <div class="actions-primary">
                            <?php if ($product->isSaleable()):?>
                                <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                <form data-role="tocart-form"
                                      data-product-sku="<?= $escaper->escapeHtml($product->getSku()) ?>"
                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                      method="post">
                                    <input type="hidden"
                                           name="product"
                                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                    <input type="hidden"
                                           name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                           value="<?=
                                           /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                           ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                            class="action tocart primary">
                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                    </button>
                                </form>
                            <?php else:?>
                                <?php if ($product->isAvailable()):?>
                                    <div class="stock available">
                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                <?php else:?>
                                    <div class="stock unavailable">
                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <?= strpos($pos, $viewMode . '-primary') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $product->getId() . ' div.actions-primary'
                            ) : '' ?>
                        <div data-role="add-to-links" class="actions-secondary">
                            <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                            <?php endif; ?>
                        </div>
                        <?= strpos($pos, $viewMode . '-secondary') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $product->getId() . ' div.actions-secondary'
                            ) : '' ?>
                    </div>
                    <?php if ($showDescription):?>
                        <div class="product description product-item-description">
                            <?= /* @noEscape */ $helper->productAttribute(
                                $product,
                                $product->getShortDescription(),
                                'short_description'
                            ) ?>
                            <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                               title="<?= /* @noEscape */ $_productNameStripped ?>"
                               class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?= strpos($pos, $viewMode . '-actions') ?
            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                $position,
                'product-item-info_' . $product->getId() . ' div.product-item-actions'
            ) : '' ?>
    </li>
<?php endforeach; ?>
